queries:
  - include: "*"
  - exclude: cpp/poorly-documented-function
  - exclude: cpp/short-global-name
  - exclude: java/index-out-of-bounds
  - exclude: java/local-shadows-field
  - exclude: java/potentially-weak-cryptographic-algorithm
  - exclude: java/uncaught-number-format-exception
  - exclude: java/unused-parameter
  - exclude: py/empty-except
  - exclude: py/redundant-global-declaration
extraction:
  python:
    python_setup:
      version: 3
